---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinyauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tinyauth
  template:
    metadata:
      labels:
        app: tinyauth
    spec:
      containers:
        - name: tinyauth
          image: ghcr.io/steveiliop56/tinyauth:v4.0.1
          ports:
            - containerPort: 3000
          env:
            - name: APP_URL
              value: "https://tinyauth.kube.local.gd:8443"
            - name: USERS
              value: user:$$2a$$10$$UdLYoJ5lgPsC0RKqYH/jMua7zIn0g9kPqWmhYayJYLaZQ/FTmH2/u # Username is user and password is password
          # livenessProbe:
          #   httpGet:
          #     path: /api/healthcheck
          #     port: 3000
          # readinessProbe:
          #   httpGet:
          #     path: /api/healthcheck
          #     port: 3000
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "125m"
              memory: "128Mi"
