---
generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/managed-by: kustomize

resources:
  - namespace.yml
  # ArgoCD Installation manifests
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - ingress.yml

patches:
  - path: patches/set-server-insecure.yml
