---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ntfy
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Ntfy
    gethomepage.dev/href: "https://ntfy.kube.dev.cturner.xyz:8443"
    gethomepage.dev/group: Monitoring
    gethomepage.dev/icon: ntfy
    gethomepage.dev/namespace: ntfy
    gethomepage.dev/app: ntfy
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ntfy.kube.dev.cturner.xyz`)
      kind: Rule
      services:
        - name: ntfy
          port: 80
  tls: {}
