---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ntfy
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ntfy.kube.local.gd`)
      kind: Rule
      services:
        - name: ntfy
          port: 80
  tls: {}
