---
namespace: ntfy

labels:
  - pairs:
      app.kubernetes.io/managed-by: argocd

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/managed-by: kustomize

configMapGenerator:
  - name: ntfy-conf
    files:
      - server.yml

resources:
  - volume.yml
  - deployment.yml
  - service.yml
  - ingress.yml
