---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  project: default

  source:
    chart: cert-manager
    repoURL: quay.io/jetstack/charts
    targetRevision: v1.18.2
    helm:
      releaseName: cert-manager
      valuesObject:
        crds:
          enabled: true

  destination:
    name: in-cluster
    namespace: cert-manager

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-cluster-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: acme-staging-cluster-issuer
spec:
  acme:
    email: "alerts@cturner.xyz"
    server: "https://acme-staging-v02.api.letsencrypt.org/directory"
    privateKeySecretRef:
      name: acme-staging-cluster-issuer-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: acme-prod-cluster-issuer
spec:
  acme:
    email: "alerts@cturner.xyz"
    server: "https://acme-v02.api.letsencrypt.org/directory"
    privateKeySecretRef:
      name: acme-prod-cluster-issuer-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-gd
spec:
  secretName: local-gd-tls

  privateKey:
    rotationPolicy: Always

  dnsNames:
    - local.gd
    - "*.local.gd"

  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kube-cturner-xyz
spec:
  secretName: kube-cturner-xyz-tls

  privateKey:
    rotationPolicy: Always

  dnsNames:
    - kube.dev.cturner.xyz
    - "*.kube.dev.cturner.xyz"

  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
