---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  project: default

  source:
    chart: cert-manager
    repoURL: quay.io/jetstack/charts
    targetRevision: v1.18.2
    helm:
      releaseName: cert-manager
      valuesObject:
        crds:
          enabled: true

  destination:
    name: in-cluster
    namespace: cert-manager

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-cluster-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-gd
spec:
  secretName: self-signed-tls

  privateKey:
    rotationPolicy: Always

  dnsNames:
    - local.gd
    - "*.local.gd"

  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
