---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
spec:
  project: default

  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: 37.0.0
    helm:
      releaseName: traefik
      valuesObject:
        ports:
          web:
            exposedPort: 8080
            redirections:
              entryPoint:
                to: websecure
                scheme: https
          websecure:
            exposedPort: 8443
            tls:
              secretName: self-signed-tls
        ingressRoute:
          dashboard:
            enabled: true
            matchRule: Host(`traefik.local.gd`)
            entryPoints:
              - websecure
            tls: {}
        providers:
          kubernetesGateway:
            enabled: true
        gateway:
          namespacePolicy: All

  destination:
    name: in-cluster
    namespace: traefik

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default

spec:
  defaultCertificate:
    secretName: self-signed-tls
