---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pocketid
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pocketid.dev.cturner.xyz`)
      kind: Rule
      services:
        - name: pocketid
          port: 1411
  tls: {}
