---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: pocketid-generator
spec:
  length: 60
  encoding: base64
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocketid-encryption-key
spec:
  refreshPolicy: OnChange
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: pocketid-generator
