---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: portainer
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`portainer.kube.dev.cturner.xyz`)
      kind: Rule
      services:
        - name: portainer
          port: 9000
  tls: {}
