---
apiVersion: approuting.kubernetes.azure.com/v1alpha1
kind: NginxIngressController
metadata:
  name: default
spec:
  controllerNamePrefix: nginx
  ingressClassName: webapprouting.kubernetes.azure.com
  defaultSSLCertificate:
    secret:
      name: "default"
      namespace: cert-manager
    forceSSLRedirect: true
