---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ../base/nginx
  - ../base/headlamp
patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: nginx
    patch: |-
      - op: replace
        path: /spec/ingressClassName
        value: traefik
      - op: replace
        path: /metadata/annotations
        value:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
      - op: replace
        path: /spec/tls/0/hosts
        value:
          - nginx.dev.cloud.cturner.xyz
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: headlamp
    patch: |-
      - op: remove
        path: /spec/values/config/oidc
      - op: replace
        path: /spec/values/ingress/ingressClassName
        value: traefik
      - op: replace
        path: /spec/values/ingress/annotations
        value: 
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
      - op: replace
        path: /spec/values/ingress/hosts
        value:
          - host: headlamp.dev.cloud.cturner.xyz
            paths:
             - path: /
               type: Prefix
