---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/headlamp
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: headlamp
    patch: |-
      - op: replace
        path: /spec/values/ingress/hosts
        value:
          - host: headlamp.localhost
            paths:
             - path: /
               type: Prefix
