---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: speedtest
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Speedtest Tracker
    gethomepage.dev/href: "https://speedtest.kube.dev.cturner.xyz:8443"
    gethomepage.dev/group: Networking
    gethomepage.dev/icon: sh-speedtest-tracker
    gethomepage.dev/namespace: speedtest
    gethomepage.dev/app: speedtest
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`speedtest.kube.dev.cturner.xyz`)
      kind: Rule
      services:
        - name: speedtest
          port: 80
  tls: {}
