---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: speedtest-generator
spec:
  length: 32
  encoding: base64
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: speedtest-app-key
spec:
  refreshPolicy: OnChange
  target:
    name: speedtest-app-key
    template:
      data:
        app_key: |
          base64:{{ .app_key }}
  dataFrom:
    - secretKey: app_key
      sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: speedtest-generator
