# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"

  config.vm.hostname = "k8s-homelab"
  config.vm.network :private_network, ip: "192.168.0.88"

  # disable default synced folder
  config.vm.synced_folder ".", "/vagrant", disabled: true
  # sync the relevant k8s files
  config.vm.synced_folder "../../", "/home/vagrant/k8s"
  config.vm.synced_folder "../../vagrant/k3s", "/home/vagrant/k8s/k3s"

  # Install k8s tools
  config.vm.provision "shell", inline: <<-SHELL
     echo "Installing helm..."

     curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

     helm version

     echo "Installed helm"

     echo "Installing k3s..."

     ufw disable

     sudo mkdir -p /etc/rancher/k3s

     sudo cp /home/vagrant/k8s/k3s/config.yml /etc/rancher/k3s/config.yaml

     curl -sfL https://get.k3s.io | sh -

     echo "Installed k3s"

     echo "alias kubectl='k3s kubectl'" > /home/vagrant/.bash_aliases
  SHELL
end
