---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
spec:
  project: default

  source:
    chart: traefik
    repoURL: ghcr.io/traefik/helm
    targetRevision: 37.0.0
    helm:
      releaseName: traefik
      skipCrds: true
      valuesObject:
        providers:
          kubernetesGateway:
            enabled: true
          kubernetesCRD:
            allowCrossNamespace: true
        gateway:
          namespacePolicy: All
        ports:
          web:
            exposedPort: 8080
            redirections:
              entryPoint:
                to: websecure
                scheme: https
                permanent: true
          websecure:
            exposedPort: 8443
            tls: {}
        ingressRoute:
          dashboard:
            enabled: true
            annotations:
              gethomepage.dev/enabled: "true"
              gethomepage.dev/name: Traefik Dashboard
              gethomepage.dev/href: "https://traefik.kube.dev.cturner.xyz:8443"
              gethomepage.dev/group: Networking
              gethomepage.dev/icon: sh-traefik
              gethomepage.dev/namespace: traefik
              gethomepage.dev/app: traefik
            matchRule: Host(`traefik.kube.dev.cturner.xyz`)
            entryPoints:
              - websecure
            tls: {}
        tlsStore:
          default:
            defaultCertificate:
              secretName: cturner-xyz-prod-tls
            certificates:
              - secretName: local-gd-tls
              - secretName: cturner-xyz-prod-tls
              - secretName: sslip-io-tls
        extraObjects:
          # Middlewares
          - # Forward authentication to tinyauth
            apiVersion: traefik.io/v1alpha1
            kind: Middleware
            metadata:
              name: oidc-auth
            spec:
              forwardAuth:
                address: http://authentik-server.authentik.svc.cluster.local/outpost.goauthentik.io/auth/traefik
                trustForwardHeader: true
                authResponseHeadersRegex: X-Authentik-*
          # Cert Manager Certificates
          - apiVersion: cert-manager.io/v1
            kind: Certificate
            metadata:
              name: local-gd
            spec:
              secretName: local-gd-tls

              privateKey:
                rotationPolicy: Always

              dnsNames:
                - local.gd
                - "*.local.gd"

              issuerRef:
                name: selfsigned-cluster-issuer
                kind: ClusterIssuer
          - apiVersion: cert-manager.io/v1
            kind: Certificate
            metadata:
              name: cturner-xyz
            spec:
              secretName: cturner-xyz-prod-tls

              privateKey:
                rotationPolicy: Always

              dnsNames:
                - kube.dev.cturner.xyz
                - "*.kube.dev.cturner.xyz"

              issuerRef:
                name: acme-prod-cluster-issuer
                kind: ClusterIssuer
          - apiVersion: cert-manager.io/v1
            kind: Certificate
            metadata:
              name: sslip-io
            spec:
              secretName: sslip-io-tls

              privateKey:
                rotationPolicy: Always

              dnsNames:
                - 10.240.222.170.sslip.io
                - "*.10.240.222.170.sslip.io"

              issuerRef:
                name: selfsigned-cluster-issuer
                kind: ClusterIssuer

  destination:
    name: in-cluster
    namespace: traefik

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
