---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
spec:
  project: default

  source:
    chart: traefik
    repoURL: ghcr.io/traefik/helm
    targetRevision: 37.0.0
    helm:
      releaseName: traefik
      skipCrds: true
      valuesObject:
        providers:
          kubernetesGateway:
            enabled: true
        gateway:
          namespacePolicy: All
        ports:
          web:
            exposedPort: 8080
            redirections:
              entryPoint:
                to: websecure
                scheme: https
                permanent: true
          websecure:
            exposedPort: 8443
            tls: {}
        ingressRoute:
          dashboard:
            enabled: true
            matchRule: Host(`traefik.kube.dev.cturner.xyz`)
            entryPoints:
              - websecure
            tls: {}
        tlsStore:
          default:
            defaultCertificate:
              secretName: cturner-xyz-tls
            certificates:
              - secretName: local-gd-tls
              - secretName: cturner-xyz-tls

  destination:
    name: in-cluster
    namespace: traefik

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
