---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
spec:
  project: default

  source:
    chart: rancher
    repoURL: https://releases.rancher.com/server-charts/stable
    targetRevision: 2.12.3
    helm:
      releaseName: rancher
      valuesObject:
        replicas: 1
        tls: external
        hostname: rancher.kube.dev.cturner.xyz
        ingress:
          enabled: true
          extraAnnotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.tls: "true"
            gethomepage.dev/enabled: "true"
            gethomepage.dev/name: Rancher
            gethomepage.dev/href: "https://rancher.kube.dev.cturner.xyz:8443"
            gethomepage.dev/group: Containers
            gethomepage.dev/icon: sh-rancher
            gethomepage.dev/namespace: cattle-system
            gethomepage.dev/app: rancher

  destination:
    name: in-cluster
    namespace: cattle-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
