---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Developer:
    - Github:
        - abbr: GH
          icon: sh-github
          href: https://github.com/
    - Github Copilot:
        - abbr: GHCP
          icon: sh-github
          href: https://github.com/copilot
    - Github Profile:
        - abbr: GHP
          icon: sh-github
          href: https://github.cturner.co.uk/
    - Github Gists:
        - abbr: GHG
          icon: sh-github
          href: https://gist.github.com/cturner8
    - Docker Hub:
        - abbr: DH
          icon: sh-docker
          href: https://hub.docker.com/

- Tools:
    - ChatGPT:
        - abbr: CGPT
          icon: sh-chatgpt
          href: https://chatgpt.com/
    - 1Password:
        - abbr: 1P
          icon: si-1password
          href: https://my.1password.com/
    - Cloudflare:
        - abbr: CF
          icon: sh-cloudflare
          href: https://dash.cloudflare.com/

- Social:
    - Reddit:
        - icon: sh-reddit
          href: https://reddit.com/

- Entertainment:
    - YouTube:
        - abbr: YT
          icon: sh-youtube
          href: https://youtube.com/
