---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nginx
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`nginx.kube.local.gd`)
      kind: Rule
      services:
        - name: nginx
          port: 80
      middlewares:
        - name: oidc-auth
          namespace: traefik
  tls: {}
