---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nginx
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: nginx
    gethomepage.dev/href: "https://nginx.kube.dev.cturner.xyz:8443"
    gethomepage.dev/group: Web
    gethomepage.dev/icon: sh-nginx
    gethomepage.dev/namespace: nginx
    gethomepage.dev/app: nginx
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`nginx.kube.dev.cturner.xyz`)
      kind: Rule
      services:
        - name: nginx
          port: 80
  tls: {}
