---
namespace: nginx

labels:
  - pairs:
      app.kubernetes.io/managed-by: argocd

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/managed-by: kustomize

resources:
  - deployment.yml
  - service.yml
  - ingress.yml
