---
apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default

spec:
  certificates:
    - secretName: local-gd-tls
    - secretName: kube-cturner-xyz-tls
  defaultCertificate:
    secretName: local-gd-tls
