---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-kustomize
  namespace: nginx-kustomize
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-kustomize
  template:
    metadata:
      labels:
        app: nginx-kustomize
    spec:
      containers:
        - name: nginx
          image: "public.ecr.aws/nginx/nginx:alpine-slim"
          ports:
            - containerPort: 80
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-kustomize
  namespace: nginx-kustomize
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx-kustomize
