---
apiVersion: kustomize.config.k8s.io/v1beta1

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/managed-by: kustomize

configMapGenerator:
  - name: oauth2-proxy
    namespace: oauth2-proxy
    files:
      - config/oauth2_proxy.cfg

resources:
  - namespace.yml
  - repository.yml
  - release.yml
