---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: valkey
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: valkey
  interval: 10m
  releaseName: valkey
  targetNamespace: oauth2-proxy
  values:
    replica:
      replicaCount: 0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: flux-system
spec:
  interval: 10m
  releaseName: oauth2-proxy
  targetNamespace: oauth2-proxy
  dependsOn:
    - name: valkey
      namespace: flux-system
  chart:
    spec:
      chart: oauth2-proxy
      version: "10.1.4"
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: flux-system
      interval: 10m
  values:
    sessionStorage:
      type: redis
      redis:
        existingSecret: valkey
        passwordKey: valkey-password
        standalone:
          connectionUrl: redis://valkey-primary:6379
    podLabels: {}
    serviceAccount:
      annotations: {}
    config: {}
    ingress:
      enabled: true
      className: webapprouting.kubernetes.azure.com
      annotations: {}
      hosts: []
      tls: []
    extraArgs:
      reverse-proxy: true
      pass-authorization-header: true
      set-xauthrequest: true
    extraVolumes:
      - name: oauth2-proxy-cookie-secret
        secret:
          secretName: oauth2-proxy-cookie-secret
    extraVolumeMounts:
      - name: oauth2-proxy-cookie-secret
        mountPath: /run/secrets/oauth2-proxy-cookie-secret
        readOnly: true
    extraObjects:
      - apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        metadata:
          name: oauth2-proxy-generator
        spec:
          length: 60
          encoding: base64
          allowRepeat: true
      - apiVersion: external-secrets.io/v1
        kind: ExternalSecret
        metadata:
          name: oauth2-proxy-cookie-secret
        spec:
          refreshPolicy: OnChange
          dataFrom:
            - sourceRef:
                generatorRef:
                  apiVersion: generators.external-secrets.io/v1alpha1
                  kind: Password
                  name: oauth2-proxy-generator
