---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  project: default

  source:
    chart: cert-manager
    repoURL: quay.io/jetstack/charts
    targetRevision: v1.18.2
    helm:
      releaseName: cert-manager
      valuesObject:
        crds:
          enabled: false
        dns01RecursiveNameserversOnly: true
        dns01RecursiveNameservers: "8.8.8.8:53,1.1.1.1:53"

  destination:
    name: in-cluster
    namespace: cert-manager

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
