---
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: flux-system

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/managed-by: kustomize

resources:
  - namespace.yml
  - repository.yml
  - release.yml
  - issuers.yml
