apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/nginx
  - ../base/oauth2-proxy
patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: nginx
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: nginx.cloud.cturner.xyz
      - op: replace
        path: /spec/tls/0/hosts
        value: 
          - nginx.cloud.cturner.xyz
      - op: replace
        path: /spec/tls/0/secretName
        value: cturner-xyz-staging-tls
      - op: replace
        path: /metadata/annotations
        value: 
          cert-manager.io/cluster-issuer: "letsencrypt-staging"
          nginx.ingress.kubernetes.io/auth-url: "https://auth.cloud.cturner.xyz/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: "https://auth.cloud.cturner.xyz/oauth2/start?rd=$scheme://$host$escaped_request_uri"
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: oauth2-proxy
    patch: |-
      - op: replace
        path: /spec/values/podLabels
        value: 
          azure.workload.identity/use: "true"
      - op: replace
        path: /spec/values/serviceAccount/annotations
        value: 
          azure.workload.identity/client-id: "${OAUTH_PROXY_IDENTITY_CLIENT_ID}"
      - op: replace
        path: /spec/values/config/clientID
        value: "${OAUTH_PROXY_CLIENT_ID}"
      - op: replace
        path: /spec/values/config/configFile
        value: |
          provider="entra-id"
          oidc_issuer_url="https://login.microsoftonline.com/${AZURE_TENANT_ID}/v2.0"
          oidc_email_claim="preferred_username"
          scope="openid profile email"
          allowed_groups=["${OAUTH_PROXY_ALLOWED_GROUP_ID}"]
          entra_id_federated_token_auth=true
          email_domains=["cturner.xyz"]
          pass_authorization_header=true
          pass_user_headers=true
          skip_provider_button=true
          reverse_proxy=true
          whitelist_domains=[".cloud.cturner.xyz"]
      - op: replace
        path: /spec/values/ingress/annotations
        value:
          cert-manager.io/cluster-issuer: "letsencrypt-staging"
      - op: replace
        path: /spec/values/ingress/hosts
        value:
          - auth.cloud.cturner.xyz
      - op: replace
        path: /spec/values/ingress/tls
        value: 
          - secretName: cturner-xyz-staging-tls
            hosts:
              - auth.cloud.cturner.xyz
