apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/nginx
patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: nginx
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: nginx.cloud.cturner.xyz
  - target:
      version: v1
      kind: PersistentVolumeClaim
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: azureblob-fuse-premium
