---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: miniflux-generator
spec:
  length: 32
  allowRepeat: true
  encoding: base64url
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miniflux-db
spec:
  refreshPolicy: OnChange
  target:
    template:
      data:
        password: "{{ .password }}"
        url: postgres://miniflux:{{ .password }}@db/miniflux?sslmode=disable
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: miniflux-generator
