---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: "https://argocd.kube.dev.cturner.xyz:8443"
  oidc.config: |
    name: "authentik"
    issuer: "https://auth.kube.dev.cturner.xyz:8443/application/o/argocd/"
    clientID: "nLsdZ95h0gDpiqT2a9U72xKrXxViirJLpYXDE2ML"
    enablePKCEAuthentication: true
    requestedScopes: ["openid", "profile", "email", "offline_access"]
