---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: "https://argocd.kube.dev.cturner.xyz:8443"
  oidc.config: |
    name: "PocketID"
    issuer: "https://pocketid.kube.dev.cturner.xyz:8443"
    clientID: "d6780869-507e-4689-8a04-f38c39ca4c0c"
    enablePKCEAuthentication: true
    requestedScopes: ["openid", "profile", "email", "groups", "offline_access"]
