---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: "https://argocd.kube.dev.cturner.xyz:8443"
  oidc.config: |
    name: "Authentik"
    issuer: "https://auth.cturner.xyz/application/o/argocd-dev/"
    clientID: "akKx3Qt0xnIowT6jciQEZ2cYuYPvXf13eaaQISO8"
    enablePKCEAuthentication: true
    requestedScopes: ["openid", "profile", "email"]
