---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
spec:
  project: default

  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: v0.20.4
    helm:
      releaseName: external-secrets
      skipCrds: true
      valuesObject: {}

  destination:
    name: in-cluster
    namespace: external-secrets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
