---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
spec:
  project: default

  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: v0.20.4
    helm:
      releaseName: external-secrets
      skipCrds: true
      valuesObject:
        extraObjects:
          - apiVersion: external-secrets.io/v1
            kind: ClusterSecretStore
            metadata:
              name: op-secret-store
              annotations:
                external-secrets.io/disable-maintenance-checks: "true"
            spec:
              provider:
                onepasswordSDK:
                  vault: K8S Homelab
                  auth:
                    serviceAccountSecretRef:
                      name: op-api-token
                      key: token
                      namespace: external-secrets

  destination:
    name: in-cluster
    namespace: external-secrets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
