---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-gd
spec:
  secretName: local-gd-tls

  privateKey:
    rotationPolicy: Always

  dnsNames:
    - local.gd
    - "*.local.gd"

  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev-cturner-xyz
spec:
  secretName: dev-cturner-xyz-tls

  privateKey:
    rotationPolicy: Always

  dnsNames:
    - kube.dev.cturner.xyz
    - "*.kube.dev.cturner.xyz"

  issuerRef:
    name: acme-cluster-issuer
    kind: ClusterIssuer
