---
namespace: cert-manager

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/managed-by: kustomize

secretGenerator:
  - name: cloudflare-api-token-secret
    envs:
      - secrets/cloudflare-api-token.env

resources:
  - issuers.yml
  - certificates.yml
