---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tools
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: IT Tools
    gethomepage.dev/href: "https://tools.kube.local.gd:8443"
    gethomepage.dev/group: Tools
    gethomepage.dev/icon: sh-it-tools
    gethomepage.dev/namespace: tools
    gethomepage.dev/app: tools
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`tools.kube.local.gd`)
      kind: Rule
      services:
        - name: tools
          port: 80
  tls: {}
