apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: nginx-keyvault-csi
spec:
  provider: azure
  secretObjects:
    - secretName: nginx-cookie-secret
      type: Opaque
      data:
        - objectName: cookie-secret
          key: cookie-secret
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ${userAssignedIdentityID}
    keyvaultName: ${keyvaultName}
    objects: |
      array:
        - |
          objectName: cookie-secret
          objectType: secret
    tenantId: ${tenantId}
