apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: nginx-keyvault-csi
spec:
  provider: azure
  secretObjects:
    - secretName: nginx-cookie-secret
      type: Opaque
      data:
        - objectName: oauth-proxy-cookie-secret
          key: cookie-secret
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 144d84a7-f37c-4365-a07b-2b35b6902726
    keyvaultName: kv-homelab-h1u3
    objects: |
      array:
        - |
          objectName: oauth-proxy-cookie-secret
          objectType: secret
    tenantId: 444ba3f3-3508-4cd5-821d-704859e285a0
