---
apiVersion: v1
kind: Namespace
metadata:
  name: speedtest
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: authentik
---
apiVersion: v1
kind: Namespace
metadata:
  name: pocketid
---
apiVersion: v1
kind: Namespace
metadata:
  name: miniflux
---
apiVersion: v1
kind: Namespace
metadata:
  name: tinyauth
