---
namespace: argocd

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/managed-by: kustomize

secretGenerator:
  - name: cloudflare-api-token-secret
    envs:
      - secrets/cloudflare-api-token.env

resources:
  - namespace.yml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - applications/cert-manager.yml
  - applications/traefik-ingress.yml
  - ingress.yml
  - applications/nginx.yml

patches:
  - path: patches/set-server-insecure.yml
