---
namespace: argocd

resources:
  - namespace.yml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - applications/traefik-ingress.yml
  - ingress.yml
  - applications/nginx.yml

patches:
  - path: patches/set-server-insecure.yml
